In [2]:
import numpy as np

In [3]:
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [4]:
print("\nORIGINAL RETAIL DATA:")


ORIGINAL RETAIL DATA:


In [5]:
print(retail_data)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [6]:
print(f"\nData shape: {retail_data.shape}")



Data shape: (10, 5)


In [8]:
print(f"Data type: {retail_data.dtype}")

Data type: float64


In [9]:
## print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
## print("\nQ1.2: Create an array of 10 zeros using np.zeros()")
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
## print("\nQ1.3: Create an array of 5 ones using np.ones()")
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [13]:
## print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")
range_array = np.arange(10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
## print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")
linspace_array = np.linspace(0, 10, 6)
print(linspace_array)

[ 0.  2.  4.  6.  8. 10.]


In [15]:
## print("\nQ2.1: What is the shape of the retail_data array?")
print(f"Shape: {retail_data.shape}")

Shape: (10, 5)


In [16]:
## print("\nQ2.2: What is the data type of the retail_data array?")
print(f"Data type: {retail_data.dtype}")


Data type: float64


In [17]:
## print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")
print(f"Size: {retail_data.size}")

Size: 50


In [18]:
## print("\nQ2.4: What is the number of dimensions of the retail_data array?")
print(f"Dimensions: {retail_data.ndim}")

Dimensions: 2


In [19]:
## print("\nQ2.5: What is the memory size of the retail_data array in bytes?")
print(f"Memory size: {retail_data.nbytes} bytes")

Memory size: 400 bytes


In [20]:
## print("\nQ3.1: Extract the first row of retail_data")
first_row = retail_data[0]
print(first_row)

[1001.     29.99   45.      4.2    15.  ]


In [21]:
## print("\nQ3.2: Extract the last row of retail_data")
last_row = retail_data[-1]
print(last_row)

[1010.     59.99   34.      4.4    10.  ]


In [22]:
## print("\nQ3.3: Extract the Price column (column index 1)")
price_column = retail_data[:, 1]
print(price_column)

[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [23]:
## print("\nQ3.4: Extract the first 3 rows and first 2 columns")
subset = retail_data[:3, :2]
print(subset)

[[1001.     29.99]
 [1002.     49.99]
 [1003.     19.99]]


In [24]:
## print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
rows_2_to_5 = retail_data[2:6]
print(rows_2_to_5)

[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


In [25]:
## print("QUESTION 4: MATHEMATICAL OPERATIONS")
print("=" * 60)

In [26]:
## print("\nQ4.1: Calculate the sum of all prices")
total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")

Total price: $481.90


In [27]:
## print("\nQ4.2: Calculate the mean price")
mean_price = np.mean(retail_data[:, 1])
print(f"Mean price: ${mean_price:.2f}")

Mean price: $48.19


In [28]:
## print("\nQ4.3: Calculate the standard deviation of prices")
std_price = np.std(retail_data[:, 1])
print(f"Standard deviation of prices: ${std_price:.2f}")

Standard deviation of prices: $24.70


In [29]:
## print("\nQ4.4: Calculate the variance of prices")
var_price = np.var(retail_data[:, 1])
print(f"Variance of prices: ${var_price:.2f}")

Variance of prices: $609.96


In [30]:
## print("\nQ4.5: Calculate the median price")
median_price = np.median(retail_data[:, 1])
print(f"Median price: ${median_price:.2f}")

Median price: $44.99


In [31]:
## print("\nQ5.1: Find the minimum and maximum prices")
min_price = np.min(retail_data[:, 1])
max_price = np.max(retail_data[:, 1])
print(f"Minimum price: ${min_price:.2f}")
print(f"Maximum price: ${max_price:.2f}")

Minimum price: $15.99
Maximum price: $89.99


In [32]:
## print("\nQ5.2: Find the minimum and maximum quantities sold")
min_qty = np.min(retail_data[:, 2])
max_qty = np.min(retail_data[:, 2])
print(f"Minimum quantity: {min_qty}")
print(f"Maximum quantity: {max_qty}")

Minimum quantity: 12.0
Maximum quantity: 12.0


In [33]:
## print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")
percentiles = np.percentile(retail_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")

25th percentile: $26.99
50th percentile: $44.99
75th percentile: $67.49


In [34]:
## print("\nQ5.4: Calculate the correlation between prices and quantities sold")
correlation = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Correlation: {correlation:.4f}")

Correlation: -0.9291


In [35]:
##  print("\nQ5.5: Calculate the covariance between prices and quantities sold")
covariance = np.cov(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")

Covariance: -653.4444


In [36]:
## print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")
reshaped_5x10 = retail_data.reshape(5, 10)
print(reshaped_5x10)

[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [37]:
## print("\nQ6.2: Flatten the retail_data to a 1D array")
flattened = retail_data.flatten()
print(flattened)

[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]


In [38]:
## print("\nQ6.3: Transpose the retail_data")
transposed = retail_data.T
print(transposed)

[[1001.   1002.   1003.   1004.   1005.   1006.   1007.   1008.   1009.
  1010.  ]
 [  29.99   49.99   19.99   89.99   15.99   69.99   39.99   79.99   25.99
    59.99]
 [  45.     32.     78.     12.     95.     28.     56.     18.     67.
    34.  ]
 [   4.2     4.5     3.8     4.7     4.      4.3     3.9     4.6     4.1
     4.4 ]
 [  15.      8.     22.      5.     18.     12.     20.      7.     16.
    10.  ]]


In [39]:
## print("\nQ6.4: Split the retail_data into 2 equal parts vertically")
split_vertical = np.vsplit(retail_data, 2)
print("First part:")
print(split_vertical[0])
print("\nSecond part:")
print(split_vertical[1])

First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [43]:
## print("\nQ6.5: Split the retail_data into 2 equal parts horizontally"))
split_horizontal = np.split(retail_data, 2)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])

First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [44]:
## print("\nQ7.1: Find products with price greater than $50")
expensive_products = retail_data[retail_data[:, 1] > 50]
print(expensive_products)

[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [45]:
## print("\nQ7.2: Find products with customer rating greater than 4.0")
high_rated = retail_data[retail_data[:, 3] > 4.0]
print(high_rated)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [46]:
## print("\nQ7.3: Find products with quantity sold greater than 50 AND price less than $40")
popular_affordable = retail_data[(retail_data[:, 2] > 50) & (retail_data[:, 1] < 40)]
print(popular_affordable)

[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [47]:
## print("\nQ7.4: Count how many products have price between $20 and $60")
price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")

Products in $20-$60 range: 5


In [48]:
## print("\nQ7.5: Find the index of the product with the highest rating")
highest_rating_idx = np.argmax(retail_data[:, 3])
print(f"Index: {highest_rating_idx}, Product ID: {retail_data[highest_rating_idx, 0]}")

Index: 3, Product ID: 1004.0


In [49]:
## print("\nQ8.1: Sort the retail_data by price (ascending)")
sorted_by_price = retail_data[retail_data[:, 1].argsort()]
print(sorted_by_price)

[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [50]:
## print("\nQ8.2: Sort the retail_data by quantity sold (descending)")
sorted_by_qty_desc = retail_data[(-retail_data[:, 2]).argsort()]
print(sorted_by_qty_desc)

[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [51]:
## print("\nQ8.3: Find the indices that would sort the array by customer rating")
rating_sort_indices = np.argsort(retail_data[:, 3])
print(rating_sort_indices)

[2 6 4 8 0 5 9 1 7 3]


In [52]:
## print("\nQ8.4: Find the product with the second highest price")
second_highest_price_idx = np.argsort(retail_data[:, 1])[-2]
second_highest_product = retail_data[second_highest_price_idx]
print(f"Product ID: {second_highest_product[0]}, Price: ${second_highest_product[1]:.2f}")

Product ID: 1008.0, Price: $79.99


In [53]:
## print("\nQ8.5: Find the product with the lowest quantity sold")
lowest_qty_idx = np.argmin(retail_data[:, 2])
lowest_qty_product = retail_data[lowest_qty_idx]
print(f"Product ID: {lowest_qty_product[0]}, Quantity: {lowest_qty_product[2]}")


Product ID: 1004.0, Quantity: 12.0


In [54]:
## print("\nQ9.2: Calculate the square root of all prices")
sqrt_prices = np.sqrt(retail_data[:, 1])
print(sqrt_prices)

[5.47631263 7.07036067 4.47101778 9.48630592 3.9987498  8.36600263
 6.3237647  8.94371288 5.09803884 7.74532117]


In [55]:
## print("\nQ9.3: Calculate the square of all quantities sold")
squared_qty = np.square(retail_data[:, 2])
print(squared_qty)

[2025. 1024. 6084.  144. 9025.  784. 3136.  324. 4489. 1156.]


In [56]:
## print("\nQ9.4: Calculate the exponential of all customer ratings")
exp_ratings = np.exp(retail_data[:, 3])
print(exp_ratings)

[ 66.68633104  90.0171313   44.70118449 109.94717245  54.59815003
  73.6997937   49.40244911  99.48431564  60.3402876   81.45086866]


In [58]:
## print("\nQ9.5: Calculate the natural logarithm of all prices")
log_prices = np.log(retail_data[:, 1])
print(log_prices)

[3.40086399 3.91182299 2.99523215 4.49969855 2.77196353 4.24835237
 3.68862942 4.38190163 3.25771185 4.09417788]
