In [2]:
import numpy as np

In [3]:
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [4]:
print("\nORIGINAL RETAIL DATA:")


ORIGINAL RETAIL DATA:


In [5]:
print(retail_data)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [6]:
print(f"\nData shape: {retail_data.shape}")



Data shape: (10, 5)


In [8]:
print(f"Data type: {retail_data.dtype}")

Data type: float64


In [9]:
## print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
## print("\nQ1.2: Create an array of 10 zeros using np.zeros()")
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
## print("\nQ1.3: Create an array of 5 ones using np.ones()")
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [13]:
## print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")
range_array = np.arange(10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
## print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")
linspace_array = np.linspace(0, 10, 6)
print(linspace_array)

[ 0.  2.  4.  6.  8. 10.]


In [15]:
## print("\nQ2.1: What is the shape of the retail_data array?")
print(f"Shape: {retail_data.shape}")

Shape: (10, 5)


In [16]:
## print("\nQ2.2: What is the data type of the retail_data array?")
print(f"Data type: {retail_data.dtype}")


Data type: float64


In [17]:
## print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")
print(f"Size: {retail_data.size}")

Size: 50


In [18]:
## print("\nQ2.4: What is the number of dimensions of the retail_data array?")
print(f"Dimensions: {retail_data.ndim}")

Dimensions: 2


In [19]:
## print("\nQ2.5: What is the memory size of the retail_data array in bytes?")
print(f"Memory size: {retail_data.nbytes} bytes")

Memory size: 400 bytes


In [20]:
## print("\nQ3.1: Extract the first row of retail_data")
first_row = retail_data[0]
print(first_row)

[1001.     29.99   45.      4.2    15.  ]


In [21]:
## print("\nQ3.2: Extract the last row of retail_data")
last_row = retail_data[-1]
print(last_row)

[1010.     59.99   34.      4.4    10.  ]


In [22]:
## print("\nQ3.3: Extract the Price column (column index 1)")
price_column = retail_data[:, 1]
print(price_column)

[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [23]:
## print("\nQ3.4: Extract the first 3 rows and first 2 columns")
subset = retail_data[:3, :2]
print(subset)

[[1001.     29.99]
 [1002.     49.99]
 [1003.     19.99]]


In [24]:
## print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
rows_2_to_5 = retail_data[2:6]
print(rows_2_to_5)

[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


In [25]:
## print("QUESTION 4: MATHEMATICAL OPERATIONS")
print("=" * 60)

In [26]:
## print("\nQ4.1: Calculate the sum of all prices")
total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")

Total price: $481.90


In [27]:
## print("\nQ4.2: Calculate the mean price")
mean_price = np.mean(retail_data[:, 1])
print(f"Mean price: ${mean_price:.2f}")

Mean price: $48.19


In [28]:
## print("\nQ4.3: Calculate the standard deviation of prices")
std_price = np.std(retail_data[:, 1])
print(f"Standard deviation of prices: ${std_price:.2f}")

Standard deviation of prices: $24.70


In [29]:
## print("\nQ4.4: Calculate the variance of prices")
var_price = np.var(retail_data[:, 1])
print(f"Variance of prices: ${var_price:.2f}")

Variance of prices: $609.96


In [30]:
## print("\nQ4.5: Calculate the median price")
median_price = np.median(retail_data[:, 1])
print(f"Median price: ${median_price:.2f}")

Median price: $44.99


In [31]:
## print("\nQ5.1: Find the minimum and maximum prices")
min_price = np.min(retail_data[:, 1])
max_price = np.max(retail_data[:, 1])
print(f"Minimum price: ${min_price:.2f}")
print(f"Maximum price: ${max_price:.2f}")

Minimum price: $15.99
Maximum price: $89.99


In [32]:
## print("\nQ5.2: Find the minimum and maximum quantities sold")
min_qty = np.min(retail_data[:, 2])
max_qty = np.min(retail_data[:, 2])
print(f"Minimum quantity: {min_qty}")
print(f"Maximum quantity: {max_qty}")

Minimum quantity: 12.0
Maximum quantity: 12.0


In [33]:
## print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")
percentiles = np.percentile(retail_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")

25th percentile: $26.99
50th percentile: $44.99
75th percentile: $67.49


In [34]:
## print("\nQ5.4: Calculate the correlation between prices and quantities sold")
correlation = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Correlation: {correlation:.4f}")

Correlation: -0.9291


In [35]:
##  print("\nQ5.5: Calculate the covariance between prices and quantities sold")
covariance = np.cov(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")

Covariance: -653.4444


In [36]:
## print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")
reshaped_5x10 = retail_data.reshape(5, 10)
print(reshaped_5x10)

[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [37]:
## print("\nQ6.2: Flatten the retail_data to a 1D array")
flattened = retail_data.flatten()
print(flattened)

[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]


In [38]:
## print("\nQ6.3: Transpose the retail_data")
transposed = retail_data.T
print(transposed)

[[1001.   1002.   1003.   1004.   1005.   1006.   1007.   1008.   1009.
  1010.  ]
 [  29.99   49.99   19.99   89.99   15.99   69.99   39.99   79.99   25.99
    59.99]
 [  45.     32.     78.     12.     95.     28.     56.     18.     67.
    34.  ]
 [   4.2     4.5     3.8     4.7     4.      4.3     3.9     4.6     4.1
     4.4 ]
 [  15.      8.     22.      5.     18.     12.     20.      7.     16.
    10.  ]]


In [39]:
## print("\nQ6.4: Split the retail_data into 2 equal parts vertically")
split_vertical = np.vsplit(retail_data, 2)
print("First part:")
print(split_vertical[0])
print("\nSecond part:")
print(split_vertical[1])

First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [43]:
## print("\nQ6.5: Split the retail_data into 2 equal parts horizontally"))
split_horizontal = np.split(retail_data, 2)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])

First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [44]:
## print("\nQ7.1: Find products with price greater than $50")
expensive_products = retail_data[retail_data[:, 1] > 50]
print(expensive_products)

[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [45]:
## print("\nQ7.2: Find products with customer rating greater than 4.0")
high_rated = retail_data[retail_data[:, 3] > 4.0]
print(high_rated)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [46]:
## print("\nQ7.3: Find products with quantity sold greater than 50 AND price less than $40")
popular_affordable = retail_data[(retail_data[:, 2] > 50) & (retail_data[:, 1] < 40)]
print(popular_affordable)

[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [47]:
## print("\nQ7.4: Count how many products have price between $20 and $60")
price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")

Products in $20-$60 range: 5


In [48]:
## print("\nQ7.5: Find the index of the product with the highest rating")
highest_rating_idx = np.argmax(retail_data[:, 3])
print(f"Index: {highest_rating_idx}, Product ID: {retail_data[highest_rating_idx, 0]}")

Index: 3, Product ID: 1004.0


In [49]:
## print("\nQ8.1: Sort the retail_data by price (ascending)")
sorted_by_price = retail_data[retail_data[:, 1].argsort()]
print(sorted_by_price)

[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [50]:
## print("\nQ8.2: Sort the retail_data by quantity sold (descending)")
sorted_by_qty_desc = retail_data[(-retail_data[:, 2]).argsort()]
print(sorted_by_qty_desc)

[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [51]:
## print("\nQ8.3: Find the indices that would sort the array by customer rating")
rating_sort_indices = np.argsort(retail_data[:, 3])
print(rating_sort_indices)

[2 6 4 8 0 5 9 1 7 3]


In [52]:
## print("\nQ8.4: Find the product with the second highest price")
second_highest_price_idx = np.argsort(retail_data[:, 1])[-2]
second_highest_product = retail_data[second_highest_price_idx]
print(f"Product ID: {second_highest_product[0]}, Price: ${second_highest_product[1]:.2f}")

Product ID: 1008.0, Price: $79.99


In [53]:
## print("\nQ8.5: Find the product with the lowest quantity sold")
lowest_qty_idx = np.argmin(retail_data[:, 2])
lowest_qty_product = retail_data[lowest_qty_idx]
print(f"Product ID: {lowest_qty_product[0]}, Quantity: {lowest_qty_product[2]}")


Product ID: 1004.0, Quantity: 12.0


In [54]:
## print("\nQ9.2: Calculate the square root of all prices")
sqrt_prices = np.sqrt(retail_data[:, 1])
print(sqrt_prices)

[5.47631263 7.07036067 4.47101778 9.48630592 3.9987498  8.36600263
 6.3237647  8.94371288 5.09803884 7.74532117]


In [55]:
## print("\nQ9.3: Calculate the square of all quantities sold")
squared_qty = np.square(retail_data[:, 2])
print(squared_qty)

[2025. 1024. 6084.  144. 9025.  784. 3136.  324. 4489. 1156.]


In [56]:
## print("\nQ9.4: Calculate the exponential of all customer ratings")
exp_ratings = np.exp(retail_data[:, 3])
print(exp_ratings)

[ 66.68633104  90.0171313   44.70118449 109.94717245  54.59815003
  73.6997937   49.40244911  99.48431564  60.3402876   81.45086866]


In [58]:
## print("\nQ9.5: Calculate the natural logarithm of all prices")
log_prices = np.log(retail_data[:, 1])
print(log_prices)

[3.40086399 3.91182299 2.99523215 4.49969855 2.77196353 4.24835237
 3.68862942 4.38190163 3.25771185 4.09417788]


In [59]:
print("\nQ10.1: Calculate the cumulative sum of prices")
cumsum_prices = np.cumsum(retail_data[:, 1])
print(cumsum_prices)


Q10.1: Calculate the cumulative sum of prices
[ 29.99  79.98  99.97 189.96 205.95 275.94 315.93 395.92 421.91 481.9 ]


In [60]:
print("\nQ10.3: Calculate the difference between consecutive prices")
print("Answer:")
diff_prices = np.diff(retail_data[:, 1])
print(diff_prices)


Q10.3: Calculate the difference between consecutive prices
Answer:
[ 20. -30.  70. -74.  54. -30.  40. -54.  34.]


In [61]:
print("\nQ10.4: Calculate the gradient of prices")
print("Answer:")
gradient_prices = np.gradient(retail_data[:, 1])
print(gradient_prices)


Q10.4: Calculate the gradient of prices
Answer:
[ 20.  -5.  20.  -2. -10.  12.   5.  -7. -10.  34.]


In [62]:


print("\nQ10.5: Calculate the histogram of prices with 5 bins")
print("Answer:")
hist_prices, bin_edges = np.histogram(retail_data[:, 1], bins=5)
print(f"Histogram counts: {hist_prices}")
print(f"Bin edges: {bin_edges}")


Q10.5: Calculate the histogram of prices with 5 bins
Answer:
Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]


In [63]:
print("\nQ11.1: Generate 5 random integers between 1 and 100")
print("Answer:")
random_ints = np.random.randint(1, 101, 5)
print(random_ints)


Q11.1: Generate 5 random integers between 1 and 100
Answer:
[36  2 31 52 31]


In [64]:
print("\nQ11.2: Generate 5 random floats between 0 and 1")
print("Answer:")
random_floats = np.random.random(5)
print(random_floats)


Q11.2: Generate 5 random floats between 0 and 1
Answer:
[0.54335515 0.21502693 0.91984745 0.78646996 0.95446766]


In [65]:
print("\nQ11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)")
print("Answer:")
normal_random = np.random.normal(0, 1, 5)
print(normal_random)


Q11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)
Answer:
[-0.20946224 -0.16813822  0.67299621  1.75843589  2.90348403]


In [66]:
print("\nQ11.4: Shuffle the retail_data rows randomly")
print("Answer:")
shuffled_data = retail_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)


Q11.4: Shuffle the retail_data rows randomly
Answer:
[[1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1001.     29.99   45.      4.2    15.  ]]


In [67]:
print("\nQ11.5: Set random seed to 42 and generate 3 random numbers")
print("Answer:")
np.random.seed(42)
seeded_random = np.random.random(3)
print(seeded_random)


Q11.5: Set random seed to 42 and generate 3 random numbers
Answer:
[0.37454012 0.95071431 0.73199394]


In [68]:
print("\nQ12.1: Calculate the dot product of price and quantity columns")
print("Answer:")
dot_product = np.dot(retail_data[:, 1], retail_data[:, 2])
print(f"Dot product: {dot_product:.2f}")


Q12.1: Calculate the dot product of price and quantity columns
Answer:
Dot product: 16527.35


In [69]:
print("\nQ12.2: Calculate the cross product of first two rows")
print("Answer:")
cross_product = np.cross(retail_data[0, :3], retail_data[1, :3])
print(cross_product)


Q12.2: Calculate the cross product of first two rows
Answer:
[-1289.87 13058.   19990.01]


In [70]:
print("\nQ12.3: Calculate the norm (magnitude) of the price column")
print("Answer:")
price_norm = np.linalg.norm(retail_data[:, 1])
print(f"Price norm: {price_norm:.2f}")


Q12.3: Calculate the norm (magnitude) of the price column
Answer:
Price norm: 171.24


In [71]:
print("\nQ12.4: Create a 2x2 matrix and calculate its determinant")
print("Answer:")
matrix_2x2 = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(matrix_2x2)
print(f"Matrix:\n{matrix_2x2}")
print(f"Determinant: {determinant}")


Q12.4: Create a 2x2 matrix and calculate its determinant
Answer:
Matrix:
[[2 3]
 [1 4]]
Determinant: 5.000000000000001


In [72]:
print("\nQ12.5: Calculate the inverse of the 2x2 matrix")
print("Answer:")
inverse_matrix = np.linalg.inv(matrix_2x2)
print(f"Inverse matrix:\n{inverse_matrix}")


Q12.5: Calculate the inverse of the 2x2 matrix
Answer:
Inverse matrix:
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [73]:
print("\nQ13.1: Convert all product IDs to strings")
print("Answer:")
product_ids_str = retail_data[:, 0].astype(str)
print(product_ids_str)


Q13.1: Convert all product IDs to strings
Answer:
['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [74]:
print("\nQ13.2: Check if any product ID contains '100'")
print("Answer:")
contains_100 = np.char.find(product_ids_str, '100') >= 0
print(contains_100)


Q13.2: Check if any product ID contains '100'
Answer:
[ True  True  True  True  True  True  True  True  True False]


In [75]:
print("\nQ13.3: Convert all product IDs to uppercase (if they were strings)")
print("Answer:")
# Since they're numbers, we'll convert to string first
product_ids_upper = np.char.upper(product_ids_str)
print(product_ids_upper)


Q13.3: Convert all product IDs to uppercase (if they were strings)
Answer:
['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [76]:
print("\nQ14.3: Find products that have been in stock for more than 15 days")
print("Answer:")
long_stock = retail_data[retail_data[:, 4] > 15]
print(long_stock)


Q14.3: Find products that have been in stock for more than 15 days
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [77]:
print("\nQ14.4: Calculate the total time all products have been in stock (in days)")
print("Answer:")
total_stock_time = np.sum(retail_data[:, 4])
print(f"Total stock time: {total_stock_time} days")


Q14.4: Calculate the total time all products have been in stock (in days)
Answer:
Total stock time: 133.0 days


In [78]:
print("\nQ14.5: Find the product with the shortest time in stock")
print("Answer:")
shortest_stock_idx = np.argmin(retail_data[:, 4])
shortest_stock_product = retail_data[shortest_stock_idx]
print(f"Product ID: {shortest_stock_product[0]}, Days: {shortest_stock_product[4]}")


Q14.5: Find the product with the shortest time in stock
Answer:
Product ID: 1004.0, Days: 5.0


In [79]:
print("\nQ15.1: Apply a function to square all prices")
print("Answer:")
def square_price(x):
    return x ** 2


Q15.1: Apply a function to square all prices
Answer:


In [80]:

print("\nQ15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'")
print("Answer:")
price_labels = np.where(retail_data[:, 1] > 50, 'Expensive', 'Affordable')
print(price_labels)


Q15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'
Answer:
['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Expensive' 'Affordable' 'Expensive' 'Affordable' 'Expensive']


In [81]:
print("\nQ15.3: Use np.select to categorize products by price ranges")
print("Answer:")
conditions = [
    retail_data[:, 1] < 20,
    (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50),
    retail_data[:, 1] >= 50
]
choices = ['Budget', 'Mid-range', 'Premium']
price_categories = np.select(conditions, choices, default='Unknown')
print(price_categories)


Q15.3: Use np.select to categorize products by price ranges
Answer:
['Mid-range' 'Mid-range' 'Budget' 'Premium' 'Budget' 'Premium' 'Mid-range'
 'Premium' 'Mid-range' 'Premium']


In [82]:
print("\nQ15.4: Use np.piecewise to apply different functions based on price ranges")
print("Answer:")
def low_price(x): return x * 0.9  # 10% discount
def mid_price(x): return x * 1.0  # No change
def high_price(x): return x * 1.1  # 10% markup

discounted_prices = np.piecewise(
    retail_data[:, 1],
    [retail_data[:, 1] < 20, (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50), retail_data[:, 1] >= 50],
    [low_price, mid_price, high_price]
)
print(discounted_prices)


Q15.4: Use np.piecewise to apply different functions based on price ranges
Answer:
[29.99  49.99  17.991 98.989 14.391 76.989 39.99  87.989 25.99  65.989]


In [83]:
print("\nQ15.5: Use np.apply_along_axis to calculate the sum of each row")
print("Answer:")
row_sums = np.apply_along_axis(np.sum, 1, retail_data)
print(row_sums)


Q15.5: Use np.apply_along_axis to calculate the sum of each row
Answer:
[1095.19 1096.49 1126.79 1115.69 1137.99 1120.29 1126.89 1117.59 1122.09
 1118.39]


In [84]:
print("\nQ16.1: Concatenate two arrays horizontally using np.hstack()")
print("Answer:")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked = np.hstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Horizontally stacked: {hstacked}")


Q16.1: Concatenate two arrays horizontally using np.hstack()
Answer:
Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontally stacked: [1 2 3 4 5 6]


In [85]:
print("\nQ16.2: Concatenate two arrays vertically using np.vstack()")
print("Answer:")
vstacked = np.vstack([arr1, arr2])
print(f"Vertically stacked:\n{vstacked}")



Q16.2: Concatenate two arrays vertically using np.vstack()
Answer:
Vertically stacked:
[[1 2 3]
 [4 5 6]]


In [86]:
print("\nQ16.3: Concatenate arrays along a specific axis using np.concatenate()")
print("Answer:")
concatenated = np.concatenate([arr1, arr2], axis=0)
print(f"Concatenated along axis 0: {concatenated}")



Q16.3: Concatenate arrays along a specific axis using np.concatenate()
Answer:
Concatenated along axis 0: [1 2 3 4 5 6]


In [87]:
print("\nQ16.4: Stack arrays depth-wise using np.dstack()")
print("Answer:")
dstacked = np.dstack([arr1, arr2])
print(f"Depth-wise stacked:\n{dstacked}")



Q16.4: Stack arrays depth-wise using np.dstack()
Answer:
Depth-wise stacked:
[[[1 4]
  [2 5]
  [3 6]]]


In [88]:
print("\nQ16.5: Create a column stack using np.column_stack()")
print("Answer:")
col_stacked = np.column_stack([arr1, arr2])
print(f"Column stacked:\n{col_stacked}")



Q16.5: Create a column stack using np.column_stack()
Answer:
Column stacked:
[[1 4]
 [2 5]
 [3 6]]


In [89]:
print("\nQ17.1: Split an array into 3 equal parts using np.split()")
print("Answer:")
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(arr_to_split, 3)
print(f"Original array: {arr_to_split}")
for i, part in enumerate(split_parts):
    print(f"Part {i+1}: {part}")



Q17.1: Split an array into 3 equal parts using np.split()
Answer:
Original array: [1 2 3 4 5 6 7 8 9]
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [90]:
print("\nQ17.2: Split an array at specific indices using np.split()")
print("Answer:")
split_at_indices = np.split(arr_to_split, [3, 6])
print(f"Split at indices [3, 6]:")
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")



Q17.2: Split an array at specific indices using np.split()
Answer:
Split at indices [3, 6]:
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [91]:
print("\nQ17.3: Split an array horizontally using np.hsplit()")
print("Answer:")
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(f"Original 2D array:\n{arr_2d}")
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part {i+1}:\n{part}")



Q17.3: Split an array horizontally using np.hsplit()
Answer:
Original 2D array:
[[1 2 3]
 [4 5 6]]
Horizontal part 1:
[[1]
 [4]]
Horizontal part 2:
[[2]
 [5]]
Horizontal part 3:
[[3]
 [6]]


In [92]:
print("\nQ17.4: Split an array vertically using np.vsplit()")
print("Answer:")
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:")
for i, part in enumerate(vsplit_parts):
    print(f"Part {i+1}:\n{part}")



Q17.4: Split an array vertically using np.vsplit()
Answer:
Vertical parts:
Part 1:
[[1 2 3]]
Part 2:
[[4 5 6]]


In [93]:
print("\nQ17.5: Split an array into equal chunks using np.array_split()")
print("Answer:")
chunks = np.array_split(arr_to_split, 4)
print(f"Split into 4 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {chunk}")



Q17.5: Split an array into equal chunks using np.array_split()
Answer:
Split into 4 chunks:
Chunk 1: [1 2 3]
Chunk 2: [4 5]
Chunk 3: [6 7]
Chunk 4: [8 9]


In [94]:
print("\nQ18.1: Repeat each element of an array 3 times using np.repeat()")
print("Answer:")
repeat_elements = np.repeat(arr1, 3)
print(f"Original: {arr1}")
print(f"Repeated 3 times: {repeat_elements}")



Q18.1: Repeat each element of an array 3 times using np.repeat()
Answer:
Original: [1 2 3]
Repeated 3 times: [1 1 1 2 2 2 3 3 3]


In [95]:
print("\nQ18.2: Repeat an entire array 2 times using np.tile()")
print("Answer:")
tiled_array = np.tile(arr1, 2)
print(f"Original: {arr1}")
print(f"Tiled 2 times: {tiled_array}")



Q18.2: Repeat an entire array 2 times using np.tile()
Answer:
Original: [1 2 3]
Tiled 2 times: [1 2 3 1 2 3]


In [96]:
print("\nQ18.3: Repeat a 2D array using np.tile()")
print("Answer:")
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
print(f"Original:\n{arr_2d_small}")
print(f"Tiled (2, 3):\n{tiled_2d}")



Q18.3: Repeat a 2D array using np.tile()
Answer:
Original:
[[1 2]
 [3 4]]
Tiled (2, 3):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [97]:
print("\nQ18.4: Create a pattern using np.tile()")
print("Answer:")
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(f"Pattern: {pattern}")
print(f"Tiled 5 times: {pattern_tiled}")



Q18.4: Create a pattern using np.tile()
Answer:
Pattern: [1 0]
Tiled 5 times: [1 0 1 0 1 0 1 0 1 0]


In [98]:
print("\nQ18.5: Repeat elements with different counts using np.repeat()")
print("Answer:")
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(arr1, repeat_counts)
print(f"Original: {arr1}")
print(f"Repeat counts: {repeat_counts}")
print(f"Result: {repeated_variable}")



Q18.5: Repeat elements with different counts using np.repeat()
Answer:
Original: [1 2 3]
Repeat counts: [2, 1, 3]
Result: [1 1 2 3 3 3]


In [99]:
print("\nQ19.1: Compare two arrays for equality using np.array_equal()")
print("Answer:")
arr_a = np.array([1, 2, 3])
arr_b = np.array([1, 2, 3])
arr_c = np.array([1, 2, 4])
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Array C: {arr_c}")
print(f"A equals B: {np.array_equal(arr_a, arr_b)}")
print(f"A equals C: {np.array_equal(arr_a, arr_c)}")



Q19.1: Compare two arrays for equality using np.array_equal()
Answer:
Array A: [1 2 3]
Array B: [1 2 3]
Array C: [1 2 4]
A equals B: True
A equals C: False


In [100]:
print("\nQ19.2: Check if arrays are close using np.allclose()")
print("Answer:")
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Array D: {arr_d}")
print(f"Array E: {arr_e}")
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")



Q19.2: Check if arrays are close using np.allclose()
Answer:
Array D: [1. 2. 3.]
Array E: [1.001 2.001 3.001]
Arrays are close: True


In [101]:
print("\nQ19.3: Apply logical AND operation between arrays")
print("Answer:")
logical_and = np.logical_and(arr_a > 1, arr_a < 3)
print(f"Array: {arr_a}")
print(f"Logical AND (1 < x < 3): {logical_and}")



Q19.3: Apply logical AND operation between arrays
Answer:
Array: [1 2 3]
Logical AND (1 < x < 3): [False  True False]


In [102]:
print("\nQ19.4: Apply logical OR operation between arrays")
print("Answer:")
logical_or = np.logical_or(arr_a == 1, arr_a == 3)
print(f"Array: {arr_a}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")



Q19.4: Apply logical OR operation between arrays
Answer:
Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]


In [103]:
print("\nQ19.5: Apply logical NOT operation to an array")
print("Answer:")
logical_not = np.logical_not(arr_a == 2)
print(f"Array: {arr_a}")
print(f"Logical NOT (x != 2): {logical_not}")



Q19.5: Apply logical NOT operation to an array
Answer:
Array: [1 2 3]
Logical NOT (x != 2): [ True False  True]


In [104]:
print("\nQ20.1: Find unique elements in an array using np.unique()")
print("Answer:")
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr_with_duplicates)
print(f"Original array: {arr_with_duplicates}")
print(f"Unique elements: {unique_elements}")



Q20.1: Find unique elements in an array using np.unique()
Answer:
Original array: [1 2 2 3 3 3 4]
Unique elements: [1 2 3 4]
